---
anonymizer:
  - version: default
    logs:
      - category: engine
        namingPatterns: # Log Naming Patterns
          - distributedEngine.log 
        regexPatterns: # Regexes used to search for log entries
          - ".*Processed login for user '(.*?)'.*display name: '(.*?)'.*email address: '(.*?)'.*SINGLEMINDSERVER.(.*?)[.].*"
          - ".*Start login for user '(.*?)', profile: '(.*?)'.*SINGLEMINDSERVER.(.*?).Security.*"
          - ".*SearchError User : (.*?) Duration .*"
      - category: launcherservice
        namingPatterns:
          - Launcher
  - version: v22.0
    logs:
      - category: launcherservice
        namingPatterns: # Log Naming Patterns
          - Launcher
        regexPatterns: # Regexes used to search for log entries
          - ".*Processed login for user '(.*?)'.*display name: '(.*?)'.*email address: '(.*?)'.*SINGLEMINDSERVER.(.*?)[.].*"
          - ".*Start login for user '(.*?)', profile: '(.*?)'.*SINGLEMINDSERVER.(.*?).Security.*"
          - ".*SearchError User : (.*?) Duration .*"
...