---
anonymizer:
  - axcVersion: default
    logs:
      - kind: engine
        namingPatterns: # Log Naming Patterns
          - distributedEngine.log 
        regexPatterns: # Regexes used to search for log entries
          - ".*Processed login for user '(.*?)'.*display name: '(.*?)'.*email address: '(.*?)'.*SINGLEMINDSERVER.(.*?)[.].*"
          - ".*Start login for user '(.*?)', profile: '(.*?)'.*SINGLEMINDSERVER.(.*?).Security.*"
          - ".*SearchError User : (.*?) Duration .*"
      - kind: launcherservice
        namingPatterns:
          - Launcher
  - axcVersion: v22.0
    logs:
      - kind: launcherservice
        namingPatterns: # Log Naming Patterns
          - Launcher
        regexPatterns: # Regexes used to search for log entries
          - ".*Processed login for user '(.*?)'.*display name: '(.*?)'.*email address: '(.*?)'.*SINGLEMINDSERVER.(.*?)[.].*"
          - ".*Start login for user '(.*?)', profile: '(.*?)'.*SINGLEMINDSERVER.(.*?).Security.*"
          - ".*SearchError User : (.*?) Duration .*"
...